# Подключение базового набора правил для Flutter
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/** # Исключить сгенерированные файлы
    - test/**_test.mocks.dart # Исключить mock-файлы для тестов


linter:
  rules:
    # Общие правила
    always_specify_types: true # Явно указывать типы переменных и возвращаемых значений
    avoid_print: true # Запрет на использование print (логирование через Logger)
    prefer_final_locals: true # Использовать final для локальных переменных, если они не изменяются
    prefer_const_constructors: true # Использовать const, где это возможно
    prefer_const_literals_to_create_immutables: true # Использовать const для списков, карт и сетов
    annotate_overrides: true # Требовать @override для переопределённых методов
    omit_local_variable_types: false # Запрет на var, использовать явные типы

    # Стиль кода
    curly_braces_in_flow_control_structures: true # Использовать фигурные скобки для if/else/for
    lines_longer_than_80_chars: false # Не ограничивать длину строки (по необходимости)
    prefer_single_quotes: true # Использовать одинарные кавычки
    avoid_multiple_declarations_per_line: true # Одно объявление на строку

    # Работа с null-safety
    avoid_null_checks_in_equality_operators: true # Предотвращение ошибок сравнения с null
    prefer_null_aware_operators: true # Использовать null-aware операторы (?. ??)

    # Организация кода
    sort_constructors_first: true # Конструкторы в начале класса
    public_member_api_docs: true # Документировать публичные методы и классы
    require_trailing_commas: true # Запятые в конце параметров/элементов
    prefer_typing_uninitialized_variables: true # Типизировать неинициализированные переменные

    # Flutter-специфичные правила
    use_key_in_widget_constructors: true # Добавлять ключи в кастомные виджеты
    avoid_unnecessary_containers: true # Не добавлять лишние контейнеры
    prefer_const_declarations: true # Использовать const для неизменяемых переменных
    avoid_redundant_argument_values: true # Удалять параметры, которые совпадают с значениями по умолчанию
    prefer_is_empty: true # Использовать isEmpty вместо length == 0

    # Производительность
    unnecessary_this: true # Избегать использования this, если это не требуется

    # Асинхронность
    unawaited_futures: true # Предупреждение о неиспользуемых Future
    prefer_void_to_null: true # Использовать void вместо null для возвращаемых значений

    # Для тестов
    avoid_equals_and_hash_code_on_mutable_classes: true # Предотвращение ошибок с mutable классами
    avoid_setters_without_getters: true # Предупреждение о сеттерах без геттеров
