name: mtg_helper
description: "magic the gathering help app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.10
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  firebase_messaging: ^15.2.0
  firebase_analytics: ^11.4.0
  firebase_crashlytics: ^4.3.0
  flutter_bloc: ^9.0.0
  go_router: ^14.6.3
  dio: ^5.7.0
  provider: ^6.1.2
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.5.1
  cached_network_image: ^3.4.1
  intl: ^0.19.0


dev_dependencies:
  build_runner: ^2.3.0
  freezed: ^2.5.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/png/


