import 'package:flutter/material.dart';
import 'package:mtg_helper/features/calendar/calendar_page.dart';
import 'package:mtg_helper/utils/enums/format.dart';

final List<Tournament> tournaments = <Tournament>[
  Tournament(
    format: Format.pauper,
    club: Club.edinorog,
    city: City.moscow,
    time: const TimeOfDay(hour: 19, minute: 30),
    price: 450,
    weekday: Weekday.monday,
  ),
  Tournament(
    format: Format.pioneer,
    club: Club.edinorog,
    city: City.moscow,
    time: const TimeOfDay(hour: 19, minute: 30),
    price: 450,
    weekday: Weekday.tuesday,
  ),
  Tournament(
    format: Format.standart,
    club: Club.portal,
    city: City.moscow,
    time: const TimeOfDay(hour: 19, minute: 30),
    price: 700,
    weekday: Weekday.tuesday,
  ),
  Tournament(
    format: Format.modern,
    club: Club.portal,
    city: City.moscow,
    time: const TimeOfDay(hour: 19, minute: 30),
    price: 500,
    weekday: Weekday.wednesday,
  ),
  Tournament(
    format: Format.legacy,
    club: Club.edinorog,
    city: City.moscow,
    time: const TimeOfDay(hour: 19, minute: 30),
    price: 650,
    weekday: Weekday.wednesday,
  ),
  Tournament(
    format: Format.pauper,
    club: Club.edinorog,
    city: City.moscow,
    time: const TimeOfDay(hour: 19, minute: 30),
    price: 450,
    weekday: Weekday.wednesday,
  ),
  Tournament(
    format: Format.pauper,
    club: Club.goldfish,
    city: City.moscow,
    time: const TimeOfDay(hour: 19, minute: 30),
    price: 300,
    weekday: Weekday.thursday,
  ),
  Tournament(
    format: Format.pauper,
    club: Club.goldfish,
    city: City.moscow,
    time: const TimeOfDay(hour: 19, minute: 30),
    price: 300,
    weekday: Weekday.friday,
  ),
  Tournament(
    format: Format.standart,
    club: Club.portal,
    city: City.moscow,
    time: const TimeOfDay(hour: 19, minute: 30),
    price: 400,
    weekday: Weekday.friday,
  ),
  Tournament(
    format: Format.modern,
    club: Club.edinorog,
    city: City.moscow,
    time: const TimeOfDay(hour: 19, minute: 30),
    price: 650,
    weekday: Weekday.friday,
  ),
  Tournament(
    format: Format.legacy,
    club: Club.portal,
    city: City.moscow,
    time: const TimeOfDay(hour: 19, minute: 30),
    price: 700,
    weekday: Weekday.friday,
  ),
  Tournament(
    format: Format.other,
    club: Club.portal,
    city: City.moscow,
    time: const TimeOfDay(hour: 12, minute: 30),
    price: 1200,
    specialTournamentDate: DateTime(
      2025,
      04,
      06,
    ),
    comment: 'Хисторик турнир!',
  ),
];
