name: Add Issue to Project

on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get project ID
        id: get_project_id
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PROJECT_ID=$(gh project list --owner komarovNW --format=json | jq -r '.projects[] | select(.title=="mtghelper") | .id')
          echo "Project ID: $PROJECT_ID"
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Add issue to project
        uses: octokit/request-action@v2
        with:
          route: POST /projects/columns/cards
          column_id: ${{ steps.get_project_id.outputs.PROJECT_ID }}
          content_id: ${{ github.event.issue.id }}
          content_type: Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
