name: Add Issue to Project

on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get project ID
        id: get_project_id
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PROJECT_ID=$(gh project list --owner komarovNW --format=json | jq -r '.projects[] | select(.title=="mtghelper") | .id')
          echo "Project ID: $PROJECT_ID"
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Get column ID
        id: get_column_id
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COLUMN_ID=$(gh project column list --project-id $PROJECT_ID --format=json | jq -r '.[0].id')
          echo "Column ID: $COLUMN_ID"
          echo "COLUMN_ID=$COLUMN_ID" >> $GITHUB_ENV

      - name: Add issue to project
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "content_id": "${{ github.event.issue.id }}",
              "content_type": "Issue",
              "project_id": "$PROJECT_ID",
              "column_id": "$COLUMN_ID"
            }' \
            https://api.github.com/projects/columns/cards
