name: Add Issue to Project

on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest

    steps:
      - name: Add issue to project
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh project item-add 3 --owner komarovNW --content-id ${{ github.event.issue.node_id }}

