name: Add Issue to Project

on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth status

      - name: Add issue to project
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PROJECT_ID=$(gh project list --owner komarovNW --format=json | jq '.[] | select(.title=="mtgHelper") | .id')
          gh project item-add $PROJECT_ID --url ${{ github.event.issue.html_url }}
