name: Dart Format Check

on:
  pull_request:
    paths:
      - '**/*.dart'
  push:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Dart format
        run: dart format .
        
      - name: Check for formatting changes
        run: dart format . --set-exit-if-changed
