name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - name: Verify Flutter version
        run: flutter --version

      - name: Clean Flutter cache
        run: flutter clean

      - name: Upgrade Flutter
        run: flutter upgrade

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Check code formatting
        run: dart format --set-exit-if-changed .

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Report success
        run: echo "Build complete"
        if: success()

      - name: Report failure
        run: echo "Build failed"
        if: failure()
