name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Клонирование репозитория
      - uses: actions/checkout@v3

      # Установка Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      # Проверка установленной версии Flutter
      - name: Verify Flutter version
        run: flutter --version

      # Очистка кэша Flutter
      - name: Clean Flutter cache
        run: flutter clean

      # Обновление Flutter до последней версии
      - name: Upgrade Flutter
        run: flutter upgrade

      # Установка зависимостей
      - name: Install dependencies
        run: flutter pub get

      # Анализ кода (линтинг)
      - name: Analyze code
        run: flutter analyze

      # Проверка форматирования
      - name: Check code formatting
        run: dart format --set-exit-if-changed .

      # Проверка сборки (debug APK)
      - name: Build APK (debug)
        run: flutter build apk --debug
